CREATE TABLE PM2_USERS (USERNAME VARCHAR2(255 BYTE) NOT NULL,PASSWORD VARCHAR2(255 BYTE) NOT NULL,ISADMIN NUMBER(1,0) DEFAULT 0);
insert into PM2_USERS values('adnan', '$2b$12$OmKCGRDx2LzLcirsAA9goe2UXh5ybNFd2PVFbPDyM.IPjzF0efPme', 1);
